version: "3.8"

services:
  app:
    build:
      context: .
    ports:
      - 3000:3000
    environment:
      - MONGO_HOST=mongo
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules/
    command: npm run start:pm2-runtime

  mongo:
    image: mongo:4.4
    ports:
      - 27017:27017
    volumes:
      - mongodb:/data/db
      - mongodb_config:/data/configdb
volumes:
  mongodb:
  mongodb_config:
